### PR TITLE
Formatting the Python viewers

### PR DESCRIPTION
**Pull request by mattclarke**
No changes to functionality, I just made some adjustments to make it a bit easier to read.

To summarise, I have:
* reformatted the code to a more standard Python format
* removed the mix of single quotes and double quotes to be just just double quotes
* When checking for `None` use `is` not `==`
* Simplified some of the dictionary constructions
* Resized the GUI buttons

### CODE REVIEW

**Comment by mrkraimer** [comment]
Matt,
I have been working on a major new version of the python viewer
It is located in
https://github.com/mrkraimer/testPython
Look at 
https://github.com/mrkraimer/testPython/blob/master/PY_NTNDA_Viewer/PY_NTNDA_Viewer.md
for a description

**Comment by mattclarke** [comment]
Hi Marty.
Thanks for the update, the new version looks promising.
Let me know if you want someone to try it out when it is ready! 👍

**Comment by mrkraimer** [comment]
Send me your email address and I will let you know when  I have progress to report.
Send the message to mrkraimer@comcast.net

Marty

**Comment by mrkraimer** [comment]
The new version of the python viewer is ready for issuing a pull request.
I did take Matt's suggestion about using black so that  the code has a more standard Python format
I will close this pull request

**Pull request closed without merging**
